# Generated by Django 5.0.2 on 2024-02-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_alter_genericbasemodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedUser',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('user_id', models.UUIDField()),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
            ],
            bases=('base.basemodel',),
        ),
    ]
