# Generated by Django 5.0.2 on 2024-02-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedUserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.TextField()),
                ('request_data', models.TextField()),
                ('response_data', models.TextField()),
                ('is_successful', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
