# Generated by Django 5.0.2 on 2024-02-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheduserrequest',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
