# Generated by Django 5.0.2 on 2024-02-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_cacheduser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cacheduser',
            name='is_authenticated',
        ),
    ]
