# Generated by Django 5.0.2 on 2024-02-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_cacheduserrequest_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheduserrequest',
            name='request_type',
            field=models.TextField(default='login'),
        ),
    ]
