# Generated by Django 5.0.2 on 2024-02-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_cacheduser_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheduser',
            name='role',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
