# Generated by Django 5.0.2 on 2024-02-14 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_created_at_basemodel_date_created_and_more'),
        ('user_management', '0006_alter_cacheduser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheduser',
            name='cached_user_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
    ]
