# Generated by Django 5.0.2 on 2024-02-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_cacheduser_cached_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheduser',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
