# Generated by Django 5.0.2 on 2024-02-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_alter_cacheduser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheduser',
            name='role',
            field=models.TextField(),
        ),
    ]
