# Generated by Django 5.0.2 on 2024-02-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_alter_cacheduser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheduser',
            name='date_joined',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cacheduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
