# Generated by Django 5.0.2 on 2024-02-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_alter_genericbasemodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('genericbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.genericbasemodel')),
                ('event_type_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state')),
            ],
            bases=('base.genericbasemodel',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('genericbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.genericbasemodel')),
                ('creator_id', models.UUIDField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('venue', models.TextField()),
                ('price', models.CharField(max_length=10)),
                ('capacity', models.CharField(max_length=10)),
                ('event_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventtype')),
            ],
            bases=('base.genericbasemodel',),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('genericbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.genericbasemodel')),
                ('role_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state')),
            ],
            bases=('base.genericbasemodel',),
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('user_id', models.UUIDField()),
                ('attendee_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('ticket_attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attendee')),
                ('ticket_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state')),
            ],
            bases=('base.basemodel',),
        ),
    ]
