# Generated by Django 5.0.2 on 2024-02-14 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
