# Generated by Django 5.0.2 on 2024-02-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericbasemodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genericbasemodel',
            name='name',
            field=models.TextField(),
        ),
    ]
