# Generated by Django 5.0.2 on 2024-02-10 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('genericbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.genericbasemodel')),
            ],
            bases=('base.genericbasemodel',),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('user_id', models.UUIDField()),
                ('request_data', models.TextField()),
                ('response_data', models.TextField(null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state')),
                ('log_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.logtype')),
            ],
            bases=('base.basemodel',),
        ),
    ]
