# Generated by Django 5.0.2 on 2024-02-14 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_rename_created_at_basemodel_date_created_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('genericbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.genericbasemodel')),
                ('user_id', models.UUIDField()),
                ('target_email', models.EmailField(max_length=254)),
                ('invite_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('invite_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state')),
            ],
            bases=('base.genericbasemodel',),
        ),
    ]
